CREATE DATABASE `SSI`;

USE `SSI`;

CREATE TABLE `imie` ( `id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, `imie` VARCHAR(30) NOT NULL, `zmiana` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ); 
CREATE TABLE `nazwisko` ( `id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, `nazwisko` VARCHAR(30) NOT NULL, `zmiana` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ); 
CREATE TABLE `adres` ( `id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, `miasto` VARCHAR(30) NOT NULL, `kod_pocztowy` VARCHAR(30) NOT NULL, `adres` VARCHAR(30) NOT NULL, `zmiana` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ); 
CREATE TABLE `ubezpieczyciel` ( `id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, `ubezpieczyciel` VARCHAR(30) NOT NULL, `zmiana` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP );

CREATE TABLE `osoba_kontaktowa` (
	`id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`imie_id` INT(6) UNSIGNED,
    `nazwisko_id` INT(6) UNSIGNED,
    `adres_id` INT(6) UNSIGNED,
	`zmiana` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `pacjent` (
	`id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`imie_id` INT(6) UNSIGNED,
    `nazwisko_id` INT(6) UNSIGNED,
    `adres_id` INT(6) UNSIGNED,
    `pesel` VARCHAR(9) NOT NULL,
    `data_urodzenia` VARCHAR(9) NOT NULL,
    `osoba_kontaktowa_id` INT(6) UNSIGNED,
    `nfz` VARCHAR(9) NOT NULL,
    `ubezpieczyciel_id` int(6) UNSIGNED,
	`zmiana` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE `pacjent` ADD FOREIGN KEY (`imie_id`) REFERENCES `imie`(`id`);
ALTER TABLE `pacjent` ADD FOREIGN KEY (`nazwisko_id`) REFERENCES `nazwisko`(`id`);
ALTER TABLE `pacjent` ADD FOREIGN KEY (`adres_id`) REFERENCES `adres`(`id`);
ALTER TABLE `pacjent` ADD FOREIGN KEY (`osoba_kontaktowa_id`) REFERENCES `osoba_kontaktowa`(`id`);
ALTER TABLE `pacjent` ADD FOREIGN KEY (`ubezpieczyciel_id`) REFERENCES `ubezpieczyciel`(`id`);